counsyl/stor

- docs/release_notes.rst
- stor/__init__.py
- stor/cli.py
Initially didn't want to call it `list` because it would shadow Python
builtin but it's less confusing to use same name in object API, functional API
and CLI.
Pretty trivial PR, no instances of listpath in tests anyways (I guess since we were testing underlying functional API).
=> @wesleykendall / @phanieste
> listpath --> list

- README.md
Updates README to have a nice intro explanation and quickstart for users.  I put CLI first, but I think Python API is also great - up to you @wesleykendall  / @phanieste
> Add quickstart and brief explanation to README

- CONTRIBUTING.md
- README.md
- stor/swift.py
@wesleykendall  - adds CONTRIBUTING.md file and moves semantic versioning note to CONTRIBUTING. Having a CONTRIBUTING.md file means that it'll show a banner at the top of Pull Requests saying that there are guidelines for contributions. e.g. see here - https://github.com/blog/1184-contributing-guidelines
Also added a note that `swift_upload_options` are deprecated.
> Add contributing md

- docs/release_notes.rst
- stor/__init__.py
@wesleykendall cc @phanieste - we accidentally left in toplevel `glob()` in this library.   Since it doesn't really work at the moment (have to pass two arguments that don't really make sense), I just changed the top-level implementation to take in 2 arguments and correctly explain what they mean.
When we implement a single argument glob, we can just allow `pattern=None`.
> Clarify top-level glob signature

- docs/release_notes.rst
- stor/__init__.py
@wesleykendall cc @phanieste - ignores distribution not found errors when not pip installed, making it easier to futz around when working in develop mode.
> Ignore distribution not found errors

- .travis.yml
- docs/release_notes.rst
- setup.cfg
- stor/__init__.py
- stor/tests/test_posix.py
- stor/tests/test_swift.py
@jtratner this provides the following:
1. Integrates travis and tests against py2.7 and py3.5
2. Updates our package classifiers
3. Adds tests for the deprecated listpath and the patching we had to do for python-swiftclient
> Add travis and additional tests for 100% coverage

- docs/release_notes.rst
- stor/__init__.py
- stor/base.py
- stor/tests/test_utils.py
- stor/utils.py
Previously, a broken symlink would be generated by walkfiles, but calling getsize() on it would cause an OSError, borking uploads.  (swift CLI also prints error to console on this, but will still do bulk upload).
This PR handles broken symlink edge case correctly by skipping it in output from walk_files_and_dirs, and returning directories that are empty except for broken symlinks (still rare).
@wesleykendall to review (fixes issue we've been having in production where we were deleting a file during clean up that had a symlink pointing to it, causing upload to fail).
> Skip broken symlinks on walk files and dirs

- docs/release_notes.rst
- stor/swift.py
- stor/tests/test_swift.py
e.g.:
```
>>> stor.listdir('swift://AUTH_blah/blah')
UnauthorizedError: Container GET failed: .../v1/AUTH_blah/blah?format=json&delimiter=/ 403 Forbidden  [first 60 chars of response] <html><h1>Forbidden</h1><p>Access was denied to this resourc X-Trans-Id: txaf2eb6f8ffa94215bafc0-005805ad59
```
Makes it much easier to grep through logs for patterns and doesn't add too much to logs (but much easier than forcing users to manually get at this attribute).
=> @wesleykendall
> Always include transaction ID if available on swift error messages

- docs/release_notes.rst
- requirements.txt
I didn't add a version because I'm deferring to python-swiftclient to select the version.
> Add six to requirements.txt

- docs/release_notes.rst
- stor/swift.py
- stor/tests/test_integration_swift.py
- stor/tests/test_swift.py
SwiftStack's S3 emulation layer creates segment containers that look like `$CONTAINER+segments` on multipart uploads.  This is a third format for segment containers, in addition to swiftclient's `$CONTAINER_segments` and stor's `.segments_CONTAINER`.
I don't see any explicit docs from SwiftStack about it, just happened when I noticed weird `ABCD+segments` containers internally.
1. Added failing integration test and confirmed it failed
2. Updated code to check for segment container and confirmed integration + unit tests pass
3. Confirmed that `stor list swift://AUTH_sometenant` no longer shows `+segments` containers.
@wesleykendall @kyleabeauchamp @krhaas
> Add detection for SwiftStack-s3 style segment containers

- docs/release_notes.rst
- requirements.txt
- stor/obs.py
- stor/tests/test_integration.py
Otherwise you end up not committing files if used (granted, unPythonically) in format `something.to_csv(stor.open(mypath, 'w'))`.
Better to be non-surprising than unclean ;)
I'm totally fine with merging py3 PR before this one if it matters.
@wesleykendall / @krhaas / @kyleabeauchamp to review
cc @pkaleta
> Ensure that OBS file cleans itself up when GC'd

- Makefile
- stor/swift.py
- stor/tests/test_integration_swift.py
- stor/tests/test_swift.py
@jtratner cc @counsyl/stor 
Before this PR, there was no ability to specify multiple files for upload together with `use_manifest=True`. This PR attempts to fix that.
I've added a unit test to make sure that it works okay. Also, I've done multiple hands-on testing of this feature.
> Support uploading multiple files together with use_manifest=True.

- requirements-dev.txt
- requirements-setup.txt
- tox.ini
This only matters for internal Counsyl CI.
And remove python 3.4 which I don't think we have installed internally.
(since Travis runs it, not a big deal)
Fixes #26 
@kyleabeauchamp @wesleykendall @pkaleta  to review
> Force tox to actually run 3.5 tests

- docs/release_notes.rst
- stor/cli.py
- stor/tests/test_cli.py
Fix error message output when specifying `stor` without a command under Python 3.
props to this SO error for explaining - http://stackoverflow.com/questions/22990977/why-does-this-argparse-code-behave-differently-between-python-2-and-3
> Fix no subparser error on python3

- setup.cfg
- stor/swift.py
- stor/tests/test_swift.py
- stor/tests/test_utils.py
- stor/utils.py
@jtratner 
The goal of `stor.utils.is_writeable` is to be able to determine whether we have write access to the specified path, either local, S3 or Swift. This is useful, because using this we'd be able to check for write permissions ahead-of-time, before generating objects for upload, which might take significant amount of time.
Check the docstring and tests for more details.
> Add stor.utils.is_writeable.

- docs/release_notes.rst
- stor/obs.py
- stor/swift.py
- stor/tests/test_s3.py
- stor/tests/test_swift.py
@jtratner 
There's a bug that occurs when calling `dirname()` on top-level swift paths like `swift://` or `swift://a`:
```
Traceback (most recent call last):
File "/Users/piotr/counsyl/stor/stor/tests/test_swift.py", line 77, in test_dirname_top_level
self.assertEquals(p1.dirname(), 'swift://')
File "/Users/piotr/counsyl/stor/stor/base.py", line 151, in dirname
return self.path_class(self.path_module.dirname(self))
File "/Users/piotr/counsyl/stor/stor/obs.py", line 71, in __init__
raise ValueError('path must have %s (got %r)' % (self.drive, pth))
ValueError: path must have swift:// (got u'swift:')
```
I've fixed it by making stor return `swift://` in those cases. The alternative would be to return an empty string or `None`, but I think the current approach is more consistent with the …
> Fix SwiftPath.dirname() for top-level swift paths.

- docs/release_notes.rst
- stor/base.py
- stor/tests/test_integration.py
- stor/tests/test_integration_posix.py
- stor/tests/test_integration_swift.py
- stor/utils.py
@pkaleta @kyleabeauchamp - sets up the stor integration tests to run against POSIX as well.  This would have surfaced the issues with `stor.open()` in Python3 land way earlier :)
For now, I've added a skip test to the tests that fail in Python 3, so then @kyleabeauchamp can remove them after his PR merges and fixes the underlying problem.
(In my estimation @kyleabeauchamp I think you'd just need to add one test that opens with 'wb' and another that opens just with 'w')
I'd like to get these tests to pass (with whatever skips) as a minimal PR and then use this in your work @kyleabeauchamp .
> Run posix in integration tests

- docs/release_notes.rst
- stor/default.cfg
- stor/posix.py
- stor/s3.py
- stor/tests/test_cli.py
- stor/tests/test_integration.py
- stor/tests/test_integration_s3.py
- stor/tests/test_s3.py
- stor/tests/test_settings.py
- tox.ini
@kyleabeauchamp @pkaleta - these changes will allow us to deploy #45 finally.
Changes:
1. Allow overriding settings for S3, so we can explicitly change s3 integration tests to pull from TEST environment variables. (+ add some tests for it)
2. Change `posix.walkfiles()` to check for isfile() so that it's consistent with all other `walkfiles()` methods
3. Allow S3 Integration tests to pass by fixing regex test
> Fix Posix + S3 integration tests

- docs/release_notes.rst
- requirements-dev.txt
- stor/base.py
- stor/cli.py
- stor/obs.py
- stor/s3.py
- stor/swift.py
- stor/tests/test_cli.py
- stor/tests/test_integration.py
- tox.ini
@kyleabeauchamp @pkaleta - the implementation that I (accidentally) allowed to be deployed to PyPI as v1.5.0 forces all text to be utf-8 on OBS, which probably isn't the behavior we want to show (works on Python 3, but only if utf-8 is the encoding).
I still need to fix a couple failing tests, but I wanted to get feedback on whether this makes sense and/or is the right way to do it.
This PR:
1. adds an `encoding` argument (only for Python3 ) that allows explicitly setting encoding
2. falls back to `locale.getpreferredencoding(False)` if encoding not set
3. Confirms that `write_object()` and `read_object()` should handle bytes only. (and adds a deprecation warning for the future)
> Ensure we respect locales when reading/writing files

- .travis.yml
- Makefile
- docs/release_notes.rst
- setup.cfg
- stor/s3.py
- stor/tests/test_s3.py
- stor/tests/test_swift.py
1. Fix up test case mocks to use bytes for body data when they ought to do that
2. Change virtualenv generation so it actually respects the version that travis has sourced. (e.g., on prior builds it'd list out `python 3.6` as the global python, but then virtualenv would go pick `python2` by default when generating a venv).
3. Remove Python 3.3 Travis test because sphinx no longer supports it.
The (now-removed-from-PyPI) stor v1.5.0 had a bug in it as described in #54.  In fixing that bug, we changed to a more explicit way of handling read/write buffers (i.e., actually using type information from read/write) and using correct locale-encoding for OBS.  This introduced some additional errors, which were caught in the internal deploy pipeline and so that version was never released.
Turns out …
> Fix up python 3-compatible stor for release

- docs/release_notes.rst
- setup.cfg
Right now we only build `py2-none-any.whl`.  Now that we are python 3 compatible (for real!), we should put up `py2.py3-none-any.whl` so Python 3 can benefit from wheels too!
> Set universal flag now that we are python2/3 compatible

- stor/exceptions.py
- stor/swift.py
When we moved exceptions into a single location, we failed to move *all*
of the overlapping swift exceptions out. Before this PR, you'd get
strange behavior like this:
```
try:
stor.copy(src, dest)
except stor.exceptions.UnavailableError:
pass
except stor.swift.UnavailableError:
```
This PR fixes up the hierarchy a little bit to make it all a little more
cohesive. It does not cause any API breaks.
cc @wesleykendall @pkaleta @kyleabeauchamp
> DRY Exception Hierarchy

- docs/release_notes.rst
- stor/__init__.py
Really simple - makes `is_obs_path` part of top-level API of stor (this was an omission from earlier).
@wesleykendall or @kyleabeauchamp if you have a sec
> Expose stor.utils.is_obs_path

- docs/release_notes.rst
- stor/base.py
- stor/cli.py
- stor/s3.py
- stor/swift.py
- stor/tests/test_cli.py
- stor/tests/test_s3.py
- stor/tests/test_swift.py
to translate swift and s3 paths to HTTP paths.
(also fix up release notes because versions got off when we were not
auto-releasing)
=> @kristjaneerik @kyleabeauchamp @pkaleta @krhaas
> Add `to_url()` method on Path and `url` cli

- docs/exceptions.rst
- docs/release_notes.rst
- docs/swift.rst
- docs/toc.rst
- stor/exceptions.py
- stor/s3.py
- stor/swift.py
- stor/tests/test_s3.py
- stor/tests/test_swift.py
Previously would raise UnauthorizedError, now we raise
ObjectInColdStorageError.  This is backwards-incompatible because
previously it does not subclass UnauthorizedError. (but this is a good
thing because we no longer auto-retry when something is in cold storage)
```
›› stor cat swift://AUTH_seq_upload_prod/X5WGWBCXY_161212_D00254_1027_A/.data_manifest.csv
ObjectInColdStorageError: Object GET failed: https://swift.counsyl.com/v1/AUTH_seq_upload_prod/X5WGWBCXY_161212_D00254_1027_A/.data_manifest.csv 403 Forbidden   The operation is not valid for the object's storage class X-Trans-Id: txe76bdb09dd8f44bf8750e-005a66619e
```
Sem-Ver: api-break
cc @pkaleta @wesleykendall @krhaas
Closes #38
> Raise informative error on GETs from objects in Glacier

- Makefile
- docs/extensions.rst
- docs/release_notes.rst
- docs/toc.rst
- stor/cli.py
- stor/extensions/swiftstack.py
- stor/obs.py
- stor/tests/test_cli.py
- stor/tests/test_extensions_swiftstack.py
* Add ``stor.extensions.swiftstack`` module for translating swift paths to s3.
* Add ``convert-swiftstack`` cli tool.
See https://www.swiftstack.com/docs/admin/cluster_management/cloud_sync.html#swift-object-representation-in-s3 for more
```
›› stor convert-swiftstack --bucket=mybucket swift://AUTH_seq_upload_prod/X5WGWBCXY_161212_D00254_1027_A/.data_manifest.csv
s3://mybucket/76f1d2/AUTH_seq_upload_prod/X5WGWBCXY_161212_D00254_1027_A/.data_manifest.csv
```
```
›› stor convert-swiftstack s3://mybucket/76f1d2/AUTH_seq_upload_prod/X5WGWBCXY_161212_D00254_1027_A/.data_manifest.csv
swift://AUTH_seq_upload_prod/X5WGWBCXY_161212_D00254_1027_A/.data_manifest.csv
```
cc @kyleabeauchamp @kristjaneerik
> Swiftstack to s3 path

- docs/release_notes.rst
- requirements.txt
- stor/obs.py
- stor/tests/shared_obs.py
- stor/tests/test_s3.py
- stor/tests/test_swift.py
Previously we were creating buffers in the ``close()`` method in order
to call ``close()`` on them and/or causing uploads in the close method
in an attempt to upload an empty file. For strict compatibility with
POSIX, we probably should create an empty file if we open but do
not close an object, but this means we can potentially generate an error
in a close method in an edge case that isn't that fun.
This is not an API-breaking change, because previously we checked for
buffer.tell() in flush, so no empty files are created.
Closes #50.
> Do not generate buffers just to close them.

- stor/tests/test_integration_s3.py
Makes it possible to run s3 integration tests against your own S3 bucket + ensures that multiple test runs do not clobber each other. (previously they'd all run at $BUCKET/test, which is kinda silly)
@kyleabeauchamp @pkaleta
> Make s3 test bucket configurable + append UUID to bucket name

- README.md
- docs/release_notes.rst
- stor/__init__.py
- stor/cli.py
- stor/tests/test_posix.py
1. remove `stor.listpath` and `stor.path`, both of which have been deprecated for a long time (and we're releasing v2.0 very soon anyways!)
2. update README.md to reflect new CLI options
3. change stor cp to no longer say "Alias for copy"
@kyleabeauchamp @pkaleta cc @wesleykendall
> Remove deprecated top-level methods

- docs/release_notes.rst
- stor/exceptions.py
- stor/s3.py
- stor/swift.py
- stor/tests/test_s3.py
* Add ``stor.S3Path.restore(days, tier)`` to restore objects from Glacier to S3.
Paired with this change are two specific exceptions related to S3 restores,
``RestoreAlreadyInProgressError`` (raised when restore has already started)
and ``AlreadyRestoredError`` (raised when restoring object already in S3).
* Move ``ConflictError`` to ``stor.exceptions`` (still available under ``stor.swift``)
@pkaleta @kyleabeauchamp cc @wesleykendall
> Add S3Path.restore to restore objects from Glacier to S3

- docs/release_notes.rst
- stor/dx.py
- stor/s3.py
- stor/swift.py
@anujkumar93 to review
Only allow bytes for write_object in Python 3. Motivation is to prevent latent programming bugs (since this is essentially required for Python 3 writing to buffers anyways).
I think this may break dxpy3 a bit, but right now it's already broken for Python 3 file object reading/writing...
> Only allow bytes for write_object in Python 3

- docs/release_notes.rst
- docs/swift.rst
- stor/base.py
- stor/obs.py
- stor/swift.py
- stor/tests/test_posix.py
Some additional API breaks to round out changes you already started @anujkumar93
* ``swift_upload_kwargs``  / ``swift_upload_options`` are no longer allowed in ``OBSFile()`` or ``stor.open()``
* The only permitted arguments/keyword arguments to ``open()`` are now ``mode`` and ``encoding``.
Haven't had chance to test but will test it in a final round of DX testing...
> Simplify open arguments

- stor/obs.py
- stor/tests/test_swift.py
During fixing encoding issues for Python 3 and DX Paths, I overlooked that for swift and s3 paths, open is also delegated to OBSPath. Hence, the encoding check should only be for DX Paths in particular.
> open fix for swift and s3

- stor/tests/test_dx.py
- stor/tests/test_integration_dx.py
Updating the default value of `wait_on_close` to 0 broke the integration tests as it didn't give the files enough time to close. Corrected that.
Also noticed during integration test that when `DX_AUTH_TOKEN` is set, it's always picked up by `_wrap_dx_calls`, hence making the login auth test fail. Corrected that.
> Fixed integration tests and login_auth test

- MANIFEST.in
- docs/package_split.rst
- docs/release_notes.rst
- stor/MANIFEST.in
- stor_dx/MANIFEST.in
- stor_dx/stor_dx/__init__.py
- stor_s3/MANIFEST.in
- stor_s3/stor_s3/__init__.py
- stor_swift/MANIFEST.in
- stor_swift/stor_swift/__init__.py
@jtratner 
This PR handles the docs, left-over review comments and any other nuances that crept up after splitting the stor packages into 4 modules.
This is a continuation of the story to split stor across 4 modules : stor, stor_dx, stor_swift, stor_s3. This is done to easy the dependencies that need to be installed to use a particular fact of stor, and to make it more modular. This PR is preceded by https://github.com/counsyl/stor/pull/101 for this story, and will be followed by a PR to generate requirements.txt dynamically to pin versions.
- package_split.rst is updated to not have release_notes language, and hopefully makes things clearer
- Manifests were added for each individual package, after checking with devpi. Have not removed the manifest at the top level, though maybe probably …
> Docs and manifest update after splitting packages

- docs/release_notes.rst
- stor/dx.py
- stor/tests/test_dx.py
@jtratner @pkaleta 
This PR fixes the normpath bug in DXVirtualPath and DXCanonicalPath
Stor had a bug for DXPaths, wherein paths like DXPath('dx://project:/').normpath() errored with `TypeError: cannot concatenate 'str' and 'NoneType' objects`. This is because for such paths, the resource turns out to be None, which is then attempted to add it to a string '/' in normpath.
- Fixed the normpath function in DXVirtualPath and DXCanonicalPath through `self.resource or ''`
- Added tests for normpath
- Test suite was run successfully
> Fix for normpath for DXPath

- docs/dx.rst
- docs/release_notes.rst
- stor/base.py
- stor/cli.py
- stor/obs.py
- stor/posix.py
- stor/s3.py
- stor/swift.py
- stor/tests/test_cli.py
@jtratner CC @pkaleta 
This PR adds the canonicalize flag to list, ls and walkfiles options in the cli. Adding this flag will help in manipulating DX paths and resources. I had to add kwargs to function definitions of these 3 commands for swift, s3, posix to not break any apis. I added a few tests to depict nothing breaks for other paths even if we pass canonicalize flag. For DXPaths, I checked that the canonicalized paths are returned. For folders, the project is canonicalized, and the path to folder stays.
```
akumar$ stor ls dx://HMM_CNV_Test --canonicalize
dx://project-FK8pJ100x54yqG4x7XyK62v2:/StorTesting
dx://project-FK8pJ100x54yqG4x7XyK62v2:/parent
dx://project-FK8pJ100x54yqG4x7XyK62v2:/workflow-FPx2PgQ0x54Yq7pbBQ2Gf87K
dx://project-FK8pJ100x54yqG4x7XyK62v2:/applet-FPx2PgQ0x54bVqVzB …
```
> Add canonicalize flag to cli functions list ls walkfiles

- docs/release_notes.rst
- requirements.txt
@jtratner cc @anujkumar93 
`six.raise_from`, which we use a lot was added in `six-1.9.0`. We need to require at least this version in requirements.txt.
> Fix required version of six package.

- docs/release_notes.rst
- requirements.txt
- stor/dx.py
- stor/tests/test_integration_dx.py
@jtratner CC @pkaleta 
Since DNAnexus has integrated dxpy3 into dxpy, makes sense to get rid of dxpy3 from stor.
Passed unit and integration tests.
> updating dxpy3 to dxpy

- stor/obs.py
- stor/tests/shared_obs.py
- added `readable`, `writable`, and `seekable` methods to `OBSFile`
- tests that OBS objects opened for reading and writing:
- have the readable/writable/seekable methods
- returns True for seekable
- returns True for `readable`, False for `writable` when opened for reading
- returns False for `readable`, True for `writable` when opened for writing
> added readable, writable, and seekable methods to OBSFile to fully implement the io.IOBase interface

- stor/tests/shared_obs.py
Blank line at end of test file caused lint failure, preventing go/cd deployment.
> lint: removed blank line

- docs/release_notes.rst
- stor/dx.py
- stor/obs.py
- stor/s3.py
- stor/swift.py
- stor/tests/shared_obs.py
- stor/tests/test_dx.py
- stor/tests/test_s3.py
- stor/tests/test_swift.py
@anujkumar93  @pkaleta - adds `content_type` property for all OBS paths.
Kinda annoying to figure out what content-type header should be set to
consistently - adding method helps with that.
Sem-Ver: feature
> Add content_type property for OBS paths

- .travis.yml
- docs/release_notes.rst
- setup.cfg
Switch out python3.4 in favor of 3.7 in Travis for testing.
> Python 3.4 is EOL - long live python 3.7!

- stor/dx.py
- stor/tests/test_dx.py
@jtratner CC @krhaas 
This PR wraps the UnauthorizedError raised from dxpy's side with a more helpful message for the stor end user.
> Wrap unauthorized error with suitable message

- docs/release_notes.rst
- stor/obs.py
Really only makes sense in ``__exit__()`` (i.e., when used in ``with``
statement).
Otherwise I think you can hang main thread in a `gc` block by accident.
Thoughts on this @anujkumar93 @pkaleta ?
> For discussion: Do not block when garbage collecting OBSFile's

- docs/release_notes.rst
- stor/obs.py
1. Only call it when we've written data (i.e., there's a buffer) - fixes
issues where destructor was throwing errors. (came up when watching travis logs)
2. Only call it for WRITE_MODES (this should potential issue where
holding a DX file object in read mode would cause an extra API
request).
I'd like to double check this, but my belief on reading this is that we were previously making an additional API request to DNAnexus every time we attempted to read a DXFile object (rather than only doing it on writes).
> Fix logic around calling wait_on_close

- docs/installation.rst
- docs/release_notes.rst
- setup.cfg
- stor/cli.py
- stor/tests/test_cli.py
@pkaleta - in prep for switching to poetry as build tool (which makes it easier to do github actions anyways)
`poetry` does not support bash scripts in its `scripts` section. So
instead we add a `stor completions` command to dump to stdout (which
accomplishes essentially same purpose as previous)
> Add a `stor completions` command to generate tab completion text

- .github/workflows/pythonpackage.yml
- docs/release_notes.rst
- pyproject.toml
- stor/dx.py
- stor/obs.py
- stor/tests/cassettes_py3/TestOpen/test_valid_and_invalid_encoding_for_dnanexus.yaml
- stor/tests/test_dx.py
Raise an exception directly in `stor.open` if we have a project path.
Previously, we were raising an exception at `write_object`;
however, if you actually attempted to write data to the path, this would
result in an exception in the `__del__` method as `stor` tried to flush
data.
This also helps reduce noise from the test suite (i.e., those test annotations)
Documented changes:
* Eliminate exception in ``__del__`` method when calling ``stor.open`` on a DNAnexus project path.
* ``stor.open()`` now throws an error earlier when incorrectly calling ``open()`` on a DNAnexus project path.
> Error earlier when open() called on DXProject to fix uncaught exception in `__del__ `

- .github/workflows/pythonpackage.yml
- docs/release_notes.rst
- docs/settings.rst
- stor/default.cfg
- stor/dx.py
- stor/settings.py
- stor/tests/cassettes_py3/TestTempUrl/test_fail_on_folder.yaml
- stor/tests/cassettes_py3/TestTempUrl/test_fail_on_project.yaml
- stor/tests/cassettes_py3/TestTempUrl/test_on_file.yaml
- stor/tests/cassettes_py3/TestTempUrl/test_on_file_canonical.yaml
- stor/tests/cassettes_py3/TestTempUrl/test_on_file_named_timed.yaml
- stor/tests/cassettes_py3/TestTempUrl/test_on_file_with_proxy_url.yaml
- stor/tests/test_cli.py
- stor/tests/test_dx.py
- stor/tests/test_settings.py
Added ``DX_FILE_PROXY_URL`` and ``[dx] -> file_proxy_url`` setting to allow for constructing
DNAnexus paths with a custom gateway.  You might want this to be able to construct valid bam
paths for samtools or IGV!
Really intersted in your own file proxy gateway? Email support@dnanexus.com to request it! ;)
Also, you're encouraged to hit up the Bioinformatics Software Engineering team at Myriad to ask
about the potential to share gateway code.
Generally, usage will look like::
$ stor url dx://proj:/folder/mypath.csv
https://dl.dnanex.us/F/D/awe1323/mypath.csv
$ export DX_FILE_PROXY_URL=https://my-dnax-proxy.example.com/gateway
$ stor url dx://proj:/folder/mypath.csv
https://my-dnax-proxy.example.com/gateway/proj/folder/mypath.csv
* Now ``temp_url()`` always sets filename to virtual object …
> Add support for DNAnexus file proxy/http serving

- Makefile
@jtratner 
With this in place, we get:
```
➜  stor (fix-tagging) ✗ make version
4.0.0
```
and
```
➜  stor (master) ✗ make tag
echo "Tagging version as 4.0.0"
Tagging version as 4.0.0
git tag -a 4.0.0 -m "Version 4.0.0"
```
> Fix version generation and tag creation.

- docs/release_notes.rst
- pyproject.toml
- stor/dx.py
- stor/tests/test_dx.py
@jtratner 
Right now, [this example from the docs](https://counsyl.github.io/stor/dx.html#stor.dx.DXPath.temp_url) doesn't work, because proxy URL doesn't have a trailing slash and therefore the `gateway` part is stripped off of the generated URL:
```
In [3]: with stor.settings.use({'dx': {'file_proxy_url': 'https://my-dnax-proxy.example.com/gateway'}}): 
...:     print(stor.Path('dx://proj:/folder/mypath.csv').temp_url()) 
...:                          
https://my-dnax-proxy.example.com/proj/folder/mypath.csv
```
It does work however, if you add a trailing slash to the proxy URL:
```
In [2]: with stor.settings.use({'dx': {'file_proxy_url': 'https://my-dnax-proxy.example.com/gateway/'}}): 
...:     print(stor.Path('dx://proj:/folder/mypath.csv').temp_url()) 
...: …
```
> Add trailing slash to file_proxy_url if absent.

- stor/s3.py
@jtratner 
Now the error is:
```
FailedUploadError: an error occurred while uploading, info={'completed': [], 'failed': [{'source': 'AUTHORS', 'dest': S3Path("s3://counsyl-roi/AUTHORS"), 'success': False, 'error': FailedUploadError('Failed to upload AUTHORS to counsyl-roi/AUTHORS: An error occurred (ExpiredToken) when calling the PutObject operation: The provided token has expired.')}]}
```
as opposed to:
```
FailedUploadError: an error occurred while uploading
```
> More verbose error msg.

- .github/workflows/pythonpackage.yml
- docs/release_notes.rst
- pyproject.toml
- stor/s3.py
- stor/test.py
- stor/tests/test_s3.py
AWS lambda cannot use `multiprocessing.Pool` and `multiprocessing.Queue` as of python3.8, due to the use of `SemLock` (see [this blog post from AWS](https://aws.amazon.com/blogs/compute/parallel-processing-in-python-with-aws-lambda/)). In order to use `stor` on AWS lambda with a python3.8 runtime, we will replace use of `multiprocessing.ThreadPool` with `concurrent.futures.ThreadPoolExecutor`, which does not use SemLock.
- Updated `ThreadPool` to `ThreadPoolExecutor` in `stor/s3.py` for both `upload` and `download`.
- Updated related unit tests for upload and download.
- Added `MockFuture` and `MockExecutor` for mocking `ThreadPoolExecutor`.
- Added `tearDown()` method to `test.py::S3TestCase` to prevent mock teardown/cleanup bleed. 
- Updated `test_upload_other_error` to appropriately …
> Update stor upload, download to work on AWS lambda for python3.8 runtime

- .github/workflows/pythonpackage.yml
As it says in description, replace python 3.6 with 3.9, now that 3.6 is no longer available as a simple built-in environment on github actions.
Sadly 3.12 seemed to have an issue with installing here, so saving that for a future improvement :(
> Fix tests by removing deprecated python 3.6 from test matrix
